export { default as Hero } from './hero'
export { default as About } from './about'
export { default as ImageSection } from './image'
export { default as Services } from './services'
export { default as Team } from './team'
